### ISSUE TITLE
Why do some Emoji not render in full color?

### ISSUE THREAD

**Issue by johanbove** [Perkovec/Emoji#3]
First of all: thank you for creating this extension! I use it a lot. 👍 
I do have a question regarding it.

Some characters are not rendering in full color. Why is that?

![screen shot 2017-03-07 at 10 02 13](https://cloud.githubusercontent.com/assets/922765/23649030/340d96e2-031d-11e7-993f-c1df6d7724d0.png)

![screen shot 2017-03-07 at 10 03 19](https://cloud.githubusercontent.com/assets/922765/23649067/51f67462-031d-11e7-820f-056c81f12e82.png)

I'm on Mac OSX Sierra 10.12.3 using Visual Studio Code Version 1.10.1 (1.10.1)

**Comment by Perkovec** [comment]
@johanbove Hello! This issue caused not only on Mac OS, this is limitation of VS Code,  that can render labels only in string format. We pass unicode of emoji, VSCode rendering that as is support by your OS.
