### ISSUE TITLE
command 'emoji.indertEmoji' not found

### ISSUE THREAD

**Issue by borisyordanov** [Perkovec/Emoji#4]
I installed the extension and tried to insert an emoji. I got the error in the title.

I'm using VSC Version 1.26.0 (1.26.0) on Mac

**Comment by TTSKarlsson** [comment]
Same here.

VSCode 1.52.1

![image](https://user-images.githubusercontent.com/9962943/104736953-f03eb980-5743-11eb-8682-a48f195940ce.png)

**Comment by Perkovec** [comment]
@TTSKarlsson @borisyordanov thanks for report! Should be fixed by #1 , let me know if something went wrong
